# Generated by Django 4.0.5 on 2022-06-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(db_index=True, max_length=255)),
                ('course', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=255)),
                ('docx', models.FileField(upload_to='files/docx/')),
                ('topic', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('work_number', models.IntegerField(blank=True, null=True)),
                ('other_files', models.FileField(blank=True, upload_to='files/other/')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.category')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.subject')),
            ],
        ),
    ]
