# Generated by Django 4.0.5 on 2022-06-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='google_docx',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Посилання на файл'),
        ),
    ]
