# Generated by Django 4.0.5 on 2022-06-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорії', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'Усі файли', 'verbose_name_plural': 'Усі файли'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмети', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='files',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='files',
            name='docx',
            field=models.FileField(upload_to='files/docx/', verbose_name='Шлях до документу'),
        ),
        migrations.AlterField(
            model_name='files',
            name='other_files',
            field=models.FileField(blank=True, upload_to='files/other/', verbose_name='Дадаткові файли'),
        ),
        migrations.AlterField(
            model_name='files',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Титулка'),
        ),
        migrations.AlterField(
            model_name='files',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='files',
            name='teacher',
            field=models.CharField(max_length=255, verbose_name='Викладач'),
        ),
        migrations.AlterField(
            model_name='files',
            name='topic',
            field=models.CharField(max_length=255, null=True, verbose_name='Тема роботи'),
        ),
        migrations.AlterField(
            model_name='files',
            name='work_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер роботи'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.IntegerField(verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Назва предмету'),
        ),
    ]
